FROM golang:1.24

WORKDIR /app

RUN go install github.com/a-h/templ/cmd/templ@v0.3.865

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD [ "templ", "generate", "--watch", "--proxy", "http://localhost:8080", "--cmd", "go run ." ]
