POST 127.0.0.1:8080/api/v1/state

{
  "modules": [
    {
      "name": "my_module1",
      "services": [
        {
          "name": "my_service",
          "image": {
            "atom": {
              "string": "hello@sha256:447303ce841432eed82c13be6fd12d68127671500358bc41b1cd734e3f43b50e"
            }
          }
        }
      ]
    },
    {
      "name": "my_module2",
      "services": [
        {
          "name": "my_service",
          "image": {
            "atom": {
              "string": "hello@sha256:447303ce841432eed82c13be6fd12d68127671500358bc41b1cd734e3f43b50e"
            }
          }
        }
      ]
    }
  ]
}
