apiVersion: v1
kind: ServiceAccount
metadata:
  name: mora-admin
  namespace: mora-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mora-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # Full unrestricted access
subjects:
  - kind: ServiceAccount
    name: mora-admin
    namespace: mora-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runway
  namespace: mora-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runway
  template:
    metadata:
      labels:
        app: runway
    spec:
      serviceAccountName: mora-admin
      containers:
        - name: runway
          image: localhost:5050/runway
          ports:
            - containerPort: 8080
            - containerPort: 7331
          env:
            - name: LEVEL
              value: DEBUG
            - name: MORA_DB_HOST
              value: postgres.mora-dev:5432
            - name: MORA_EXTERNAL_REPO_URL
              value: localhost:5000
            - name: MORA_INTERNAL_REPO_URL
              value: registry.mora-dev:5000
---
apiVersion: v1
kind: Service
metadata:
  name: runway
  namespace: mora-dev
spec:
  selector:
    app: runway
  ports:
    - port: 80
      targetPort: 8080
