apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: mora-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mora-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: "mora"
            - name: POSTGRES_PASSWORD
              value: "mora"
            - name: POSTGRES_DB
              value: "mora"
          ports:
            - containerPort: 5432
              hostPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mora-dev
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
